In [3]:
import csv
import pandas as pd

# add header names
headers =  ['age', 'sex','chest_pain','resting_blood_pressure',  
        'serum_cholestoral', 'fasting_blood_sugar', 'resting_ecg_results',
        'max_heart_rate_achieved', 'exercise_induced_angina', 'oldpeak',"slope of the peak",
        'num_of_major_vessels','thal', 'heart_disease']

# load heart data
df = pd.read_csv('heart.dat', sep=' ', names=headers)
df

age  sex  chest_pain  resting_blood_pressure  serum_cholestoral  \
0    70.0  1.0         4.0                   130.0              322.0   
1    67.0  0.0         3.0                   115.0              564.0   
2    57.0  1.0         2.0                   124.0              261.0   
3    64.0  1.0         4.0                   128.0              263.0   
4    74.0  0.0         2.0                   120.0              269.0   
..    ...  ...         ...                     ...                ...   
265  52.0  1.0         3.0                   172.0              199.0   
266  44.0  1.0         2.0                   120.0              263.0   
267  56.0  0.0         2.0                   140.0              294.0   
268  57.0  1.0         4.0                   140.0              192.0   
269  67.0  1.0         4.0                   160.0              286.0   

     fasting_blood_sugar  resting_ecg_results  max_heart_rate_achieved  \
0                    0.0                  2.0                    109.0   
1                    0.0                  2.0                    160.0   
2                    0.0                  0.0                    141.0   
3                    0.0                  0.0                    105.0   
4                    0.0                  2.0                    121.0   
..                   ...                  ...                      ...   
265                  1.0                  0.0                    162.0   
266                  0.0                  0.0                    173.0   
267                  0.0                  2.0                    153.0   
268                  0.0                  0.0                    148.0   
269                  0.0                  2.0                    108.0   

     exercise_induced_angina  oldpeak  slope of the peak  \
0                        0.0      2.4                2.0   
1                        0.0      1.6                2.0   
2                        0.0      0.3                1.0   
3                        1.0      0.2                2.0   
4                        1.0      0.2                1.0   
..                       ...      ...                ...   
265                      0.0      0.5                1.0   
266                      0.0      0.0                1.0   
267                      0.0      1.3                2.0   
268                      0.0      0.4                2.0   
269                      1.0      1.5                2.0   

     num_of_major_vessels  thal  heart_disease  
0                     3.0   3.0              2  
1                     0.0   7.0              1  
2                     0.0   7.0              2  
3                     1.0   7.0              1  
4                     1.0   3.0              1  
..                    ...   ...            ...  
265                   0.0   7.0              1  
266                   0.0   7.0              1  
267                   0.0   3.0              1  
268                   0.0   6.0              1  
269                   3.0   3.0              2  

[270 rows x 14 columns]

In [7]:
# check for missing values
df.isna().sum()

age                        0
sex                        0
chest_pain                 0
resting_blood_pressure     0
serum_cholestoral          0
fasting_blood_sugar        0
resting_ecg_results        0
max_heart_rate_achieved    0
exercise_induced_angina    0
oldpeak                    0
slope of the peak          0
num_of_major_vessels       0
thal                       0
heart_disease              0
dtype: int64

In [8]:
df.dtypes

age                        float64
sex                        float64
chest_pain                 float64
resting_blood_pressure     float64
serum_cholestoral          float64
fasting_blood_sugar        float64
resting_ecg_results        float64
max_heart_rate_achieved    float64
exercise_induced_angina    float64
oldpeak                    float64
slope of the peak          float64
num_of_major_vessels       float64
thal                       float64
heart_disease                int64
dtype: object

In [22]:
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# split into train and test set
X = df.drop(columns='heart_disease')

# label target class with 0, 1 instead of 1, 2
df.heart_disease = df.heart_disease.replace(1,0)
df.heart_disease = df.heart_disease.replace(2, 1)

y = df.heart_disease

X_train, X_test, y_train, y_test = train_test_split(X, y, )

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((202, 13), (68, 13), (202,), (68,))

In [30]:
from sklearn.preprocessing import StandardScaler

# standardize the dataset
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [33]:
X_train

array([[-0.09503519,  0.68880516,  0.89817539, ...,  0.71181012,
         1.33307352, -0.83020579],
       [ 0.1268967 ,  0.68880516,  0.89817539, ...,  0.71181012,
         0.30134612,  0.73223119],
       [-1.20469468, -1.45178935, -0.1566585 , ...,  0.71181012,
        -0.73038128, -0.83020579],
       ...,
       [-0.09503519,  0.68880516,  0.89817539, ...,  0.71181012,
         0.30134612,  1.25304352],
       [ 0.1268967 ,  0.68880516, -2.26632626, ...,  0.71181012,
        -0.73038128,  1.25304352],
       [ 0.45979455,  0.68880516,  0.89817539, ...,  0.71181012,
         0.30134612,  1.25304352]])

In [46]:
def relu(X):
  '''
    Relu activation function
  '''
  return np.maximum(0, X)

relu([-1, 0, 1])

array([0, 0, 1])

In [53]:
def sigmoid(X):
  return 1/(1+np.exp(-X))

for x in [1, 2, 3]:
  print(x, sigmoid(x), sigmoid(-x))

1 0.7310585786300049 0.2689414213699951
2 0.8807970779778823 0.11920292202211755
3 0.9525741268224334 0.04742587317756678


In [104]:
def sigmoid_derivative(X):
  return sigmoid(X) * (1 - sigmoid(X))

In [102]:
def relu_derivative(X):
  x[x <= 0] = 0
  x[x > 0] = 1
  return x

In [117]:
def cross_entropy_loss(y, y_hat):
  '''
    Binary cross entropy loss
  '''
  log = np.log
  return -y*log(y_hat) - (1-y)*log(1-y_hat)

In [122]:
cross_entropy_loss(np.array([1, 1]), np.array([1e-9,0.2]))

array([20.72326584,  1.60943791])

In [127]:
def cross_entropy_loss_derivative(y, y_hat):
  return -y / y_hat + (1-y)/(1-y_hat)

In [130]:
class Layer():
  def __init__(self, input_size, output_size, activation_function, activation_function_derivative):
    # Initialize weights and biases from a normal distribution
    self.W = np.random.randn(input_size, output_size)
    self.b = np.random.randn(output_size)
    self.activation_function = activation_function
    self.activation_function_derivative = activation_function_derivative

  def forward(self, input):
    z = input.dot(self.W) + self.b
    return self.activation_function(z)
  
  def backward(self, loss_derivative):
    dZ = self.activation_function_derivative(loss_derivative)
    dW = np.dot(self.W.T, dZ)
    return dZ

layer = Layer(5, 1, activation_function=sigmoid, activation_function_derivative=sigmoid_derivative)
input = np.random.randn(5)
output = layer.forward(input)
loss_derivative = cross_entropy_loss_derivative(np.array([1, 1]), output)
print(input)
print(output)
print(loss_derivative)
layer.backward(loss_derivative)

[ 0.89823837 -0.7068522  -1.34491232  0.32665849 -0.66907644]
[0.5749123]
[-1.73939573 -1.73939573]


array([0.12707242, 0.12707242])

In [109]:
class NeuralNetwork():
  def __init__(self, layers, learning_rate=0.001, iterations=100):
    self.layers = layers
    self.learning_rate = learning_rate
    self.iterations = iterations

  def forward(self, input):
    for layer in self.layers:
      input = layer.forward(input)
    return input

input = np.random.randn(13)
hidden_layer = Layer(13, 8, activation_function=relu, activation_function_derivative=relu_derivative)
output_layer = Layer(8, 1, activation_function=sigmoid, activation_function_derivative=sigmoid_derivative)
neural_network = NeuralNetwork([hidden_layer, output_layer])

neural_network.forward(input)

array([7.92569545e-07])

In [94]:
neural_network.forward(X.to_numpy())

C:\Users\bpech\AppData\Local\Temp\ipykernel_22668\535879097.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


array([[2.62793196e-220, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [1.57923839e-176, 1.00000000e+000],
       [3.09084147e-179, 1.00000000e+000],
       [3.96428243e-190, 1.00000000e+000],
       [6.97129108e-142, 1.00000000e+000],
       [3.76691220e-182, 1.00000000e+000],
       [3.55518440e-167, 1.00000000e+000],
       [9.33307733e-206, 1.00000000e+000],
       [1.02092618e-259, 1.00000000e+000],
       [3.14359945e-174, 1.00000000e+000],
       [8.18776609e-175, 1.00000000e+000],
       [2.48607283e-188, 1.00000000e+000],
       [2.81380063e-170, 1.00000000e+000],
       [4.48202311e-214, 1.00000000e+000],
       [4.90337044e-132, 1.00000000e+000],
       [1.68206302e-204, 1.00000000e+000],
       [1.03724492e-164, 1.00000000e+000],
       [2.32644694e-156, 1.00000000e+000],
       [6.39341547e-154, 1.00000000e+000],
       [3.65714231e-165, 1.00000000e+000],
       [4.68783499e-185, 1.00000000e+000],
       [8.74231323e-206, 1.00000000e+000],
       [8.4