In [1]:
import numpy as np

np.tanh([1, 0, -1])

array([ 0.76159416,  0.        , -0.76159416])

In [9]:
predictions = np.array([[1.1], [0.9], [1]])
true_values = np.array([[1], [1], [1]])

1 * (predictions > true_values) + -1 * (predictions < true_values)

array([[ 1],
       [-1],
       [ 0]])

In [2]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[1,2,3], [4,5,6]])
a.shape, b.shape

((3, 2), (2, 3))

In [3]:
a, b

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [4]:
a * b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [5]:
a * a

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [6]:
a.T @ np.array([1,2,3])

array([22, 28])

In [7]:
a @ b

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [8]:
a @ np.array([[1, 2]]).T

array([[ 5],
       [11],
       [17]])

In [9]:
a @ np.array([1,2])

array([ 5, 11, 17])

In [19]:
dL_dY = np.array([[7, 7], [14, 14]])
np.sum(dL_dY), np.sum(dL_dY, axis=0), np.sum(dL_dY, axis=0, keepdims=True)

(42, array([21, 21]), array([[21, 21]]))

In [21]:
np.random.randn(1, 2)

array([[ 1.11637296, -0.36559655]])

In [26]:
input = np.array([-1, 0, 0.2, 0])
np.sum(input == 0)

2